### PR TITLE
I 888 mean auto

### PR DESCRIPTION
**Pull request by AndreasLMeg**

### CODE REVIEW

**Review by EricClaeys — CHANGES_REQUESTED** [review]
To be consistent with other settings that have a day and night version, please name them -daymean-value and -nightmean-value.  And the .cpp variables should be likewise named.
In the printf() of their vales, use `Mean Value (day)` and `Mean Value (night)` to be consistent.

Thanks for adding day gain. We should probably implement the other day/night settings like dayautoexposure, dayexposure, daymaxautoexposure, nightmaxautoexposure, daymaxgain, and nightmaxgain. The autoexposure algorithm would use the "max" values.

The li es you added for "init mean" in the daytime and nighttime initialization sections can probably be combined and moved below using the "currentExposure_us, currentGain, and other similar variables.

I think line 1773 should use the "max" values when we implement them, not the current values.  Agree?

You can combine mock_endOfNight.sh and mock_saveImage.sh into a generic "mock_script.sh" that mocks any script in allsky/scripts by passing the name of the script on the command line, then replacing the hard-coded names with the passed in argument. 
Also, if that script source's $ALLSKY_HOME/variables.sh, you can use $ALLSKY_SCRIPTS.

Mock_sunwait.sh:  don't we have our own version in ~/allsky?

**Comment by AndreasLMeg** [comment]
> I think line 1773 should use the "max" values when we implement them, not the current values. Agree?

I interprete the "current" values as the "current settings"  depending on day/night. They only change when day or night starts.

**Comment by AndreasLMeg** [comment]
> Mock_sunwait.sh: don't we have our own version in ~/allsky?

For testing I replace sunwait with my sunwait "script" with one variable I can change the return value to "DAY" or "NIGHT"

**Comment by AndreasLMeg** [comment]
> To be consistent with other settings that have a day and night version, please name them -daymean-value and -nightmean-value. And the .cpp variables should be likewise named.
> In the printf() of their vales, use `Mean Value (day)` and `Mean Value (night)` to be consistent.

Yes, I will do that

**Comment by AndreasLMeg** [comment]
> Thanks for adding day gain. We should probably implement the other day/night settings like dayautoexposure, dayexposure, daymaxautoexposure, nightmaxautoexposure, daymaxgain, and nightmaxgain. The autoexposure algorithm would use the "max" values.

If mean and auto are used, the daygain/nightgain, dayexposure, nightexposure (current) are used as max values
If mean and no auto is used, mean control is OFF and daygain/nightgain, dayexposure, nightexposure (current) are used as values. 

So, i think there is no use for extra max values

**Comment by AndreasLMeg** [comment]
> You can combine mock_endOfNight.sh and mock_saveImage.sh into a generic "mock_script.sh" that mocks any script in allsky/scripts by passing the name of the script on the command line, then replacing the hard-coded names with the passed in argument.
> Also, if that script source's $ALLSKY_HOME/variables.sh, you can use $ALLSKY_SCRIPTS.

under construction....

**Review by EricClaeys — CHANGES_REQUESTED** [review]
Andreas, doesn't the saveImage.sh chane in this PR need to be removed so it doesn't overwrite the corrected fix?

**Comment by AndreasLMeg** [comment]
> Andreas, doesn't the saveImage.sh chane in this PR need to be removed so it doesn't overwrite the corrected fix?

I keep the branch up to date.
This branch is still a work in progress/test and will not be completely merged (MOCK)

But I wanted to inform you about changes in advance (pair programming)

**Comment by AndreasLMeg** [comment]
@EricClaeys What's you opinion: ready for pullrequest ?

**Comment by EricClaeys** [comment]
I will have to spend time looking at it.  There are a lot of commits, but I think many of them are to keep your fork up-to-date.  Is that correct?

**Comment by AndreasLMeg** [comment]
Hello Eric,

 

yes during development and testing and updating, I  have seen some other problems,.... thats the reason for the commits


 

Maybe this view is better to get the overview: https://github.com/AndreasLMeg/allsky/pull/9/files

 

The PR to allsky will be a single commit.

 

 

Gesendet: Sonntag, 23. Januar 2022 um 09:19 Uhr
Von: "EricClaeys" ***@***.***>
An: "AndreasLMeg/allsky" ***@***.***>
Cc: "AndreasLMeg" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [AndreasLMeg/allsky] I 888 mean auto (PR #9)


 

I will have to spend time looking at it. There are a lot of commits, but I think many of them are to keep your fork up-to-date. Is that correct?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
